---

- name: Drop any existing mysql database for 'test' environment
  mysql_db:
    name: "{{ database_name }}"
    state: absent
    login_user: "{{ database_provisioning_username }}"
    login_password: "{{ database_provisioning_password }}"
  when: environment_name == "test"

- name: Create mysql database
  mysql_db:
    login_user: "{{ database_provisioning_username }}"
    login_password: "{{ database_provisioning_password }}"
    name: "{{ database_name }}"
    state: present

# ignore_errors is workaround for condition where we cannot create user due mysql auth check and user was created manually
# at some point.
- name: Create mysql user
  mysql_user:
    login_user: "{{ database_provisioning_username }}"
    login_password: "{{ database_provisioning_password }}"
    name: "{{ database_username }}"
    password: "{{ database_username }}"
    priv: "*.*:ALL"
    state: present
  ignore_errors: yes
  when: environment_name != "demo"
