---

- name: Stop tomcat
  service:
    name: "{{ tomcat_service }}"
    state: stopped
    pattern: "{{ tomcat_service }}"

- name: Create release directory
  file:
    path: "{{ releases_folder }}"
    state: directory

- name: Download liquibase-runner-{{ version }}.zip
  get_url:
    url: https://build-inera.nordicmedtest.se/nexus/repository/{{ repo }}/se/inera/rehabstod/rehabstod-liquibase-runner/{{ version }}/rehabstod-liquibase-runner-{{ version }}.zip
    dest: "{{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}.zip"
  when: deploy_from_repo|bool

- name: Copy rehabstod-liquibase-runner-{{ version }}.zip
  copy:
    src: "{{ playbook_dir }}/../tools/liquibase-runner/build/distributions/rehabstod-liquibase-runner-{{ version }}.zip"
    dest: "{{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}.zip"
  when: not deploy_from_repo|bool

- name: Unzip liquibase-runner-{{ version }}.zip
  unarchive:
    src: "{{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}.zip"
    dest: "{{ releases_folder }}"
    creates: "{{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}/bin/liquibase-runner"
    remote_src: yes

- name: Run liquibase update
  command: "{{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}/bin/rehabstod-liquibase-runner --url={{ database_url }} --username={{ database_username }} --password={{ database_password }} update"
  args:
      chdir: "{{ releases_folder }}/rehabstod-liquibase-runner-{{ version }}"
  environment:
      JAVA_HOME: "{{ java_home }}"

- name: Download rehabstod-web-{{ version }}.war
  get_url:
    url: "https://build-inera.nordicmedtest.se/nexus/repository/{{ repo }}/se/inera/intyg/rehabstod/rehabstod-web/{{ version }}/rehabstod-web-{{ version }}.war"
    dest: "{{ releases_folder }}/rehabstod-web-{{ version }}.war"
    timeout: 60
  when: deploy_from_repo|bool

- name: Copy rehabstod-web-{{ version }}.war from THIS machine when not deploying from remote repo
  copy:
    src: "{{ playbook_dir }}/../web/build/libs/rehabstod-web-{{ version }}.war"
    dest: "{{ releases_folder }}/rehabstod-web-{{ version }}.war"
  when: not deploy_from_repo|bool

- name: Remove old version of unpacked rehabstod war
  file:
    state: absent
    path: "{{ webapps_folder }}/ROOT"

- name: Deploy rehabstod-web-{{ version }}.war as ROOT.war in {{ webapps_folder }}
  copy:
    src: "{{ releases_folder }}/rehabstod-web-{{ version }}.war"
    dest: "{{ webapps_folder }}/ROOT.war"
    remote_src: True

- name: Remove rehabstod-web-{{ version }}.war from releases
  file:
    state: absent
    path: "{{ releases_folder }}/rehabstod-web-{{ version }}.war"

- name: Create version file
  template:
    src: version.txt.j2
    dest: "{{ webapps_folder }}/version.txt"

- name: Update configuration to {{ config_version }}
  git:
    repo: "{{ config_repository }}"
    dest: "{{ config_folder }}"
    version: "{{ config_version }}"

- name: Start tomcat
  service:
    name: "{{ tomcat_service }}"
    state: started
    pattern: "{{ tomcat_service }}"
