apiVersion: v1
data:
  BROKER_AMQ_TCP_PORT: tcp://activemq-amq-tcp:61616
  NTJP_WS_CERTIFICATE_TYPE: JKS
  NTJP_WS_TRUSTSTORE_TYPE: JKS
kind: ConfigMap
metadata:
  name: rehabstod-demo-configmap-envvar
type: Opaque
