---
# file: roles/rehabstod-systemvariabler/tasks/main.yml

- name: Create rehabstod-env.sh file
  template: src=rehabstod-env.sh.j2 dest="{{ inera_tomcat_folder }}/rehabstod-env.sh" mode=755

- name: configure setenv.sh
  lineinfile:
    dest="{{ tomcat_bin }}/setenv.sh"
    create=yes
    mode=755
    regexp="rehabstod-env\.sh"
    insertafter="EOF"
    line=". \"{{ inera_tomcat_folder }}/rehabstod-env.sh\""

