---

- name: Create rehabstod-env.sh file
  template:
    src: rehabstod-env.sh.j2
    dest: "{{ inera_tomcat_folder }}/rehabstod-env.sh"
    mode: 0755

- name: Configure setenv.sh
  lineinfile:
    dest: "{{ tomcat_bin }}/setenv.sh"
    regexp: "rehabstod-env\\.sh"
    insertafter: "EOF"
    line: ". \"{{ inera_tomcat_folder }}/rehabstod-env.sh\""
    create: yes
    mode: 0755
