# This playbook deploys rehabstod

- hosts: rehabstod-tomcat
  sudo: yes
  vars:
    # repo - values: 'snapshots or 'releases'
    repo: releases
    version: 1.0.0-b27
    config_version: master

  roles:
    - app-resources
    - rehabstod
