# This playbook deploys rehabstod

- hosts: tomcat
  become: yes
  serial: 1
  environment:
    "{{ proxy_env }}"
  vars:
    repo: releases
    config_version: master

  roles:
    - app-resources
    - rehabstod
