---
# This playbook provisions Tomcat resources for Rehabstöd

- hosts: rehabstod-tomcat
  sudo: yes 

  roles:
    - rehabstod-systemvariabler
    - rehabstod-resurser
    - rehabstod-jarfiler
    - config-folder
