---

- hosts: tomcat
  serial: 1
  become: yes 
  environment:
    "{{ proxy_env }}"
  roles:
    - rehabstod-systemvariabler
    - rehabstod-resurser
    - rehabstod-jarfiler
    - config-folder
    - unlock-config-folder
